// <auto-generated />
using BulkyWeb_Razor.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BulkyWeb_Razor.Migrations
{
    [DbContext(typeof(MyDBContext))]
    partial class MyDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BulkyWeb_Razor.Models.Relative", b =>
                {
                    b.Property<int>("RelativeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RelativeId"));

                    b.Property<string>("Relationship")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("RelativeName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("RelativeId");

                    b.ToTable("RelativesTable");

                    b.HasData(
                        new
                        {
                            RelativeId = 1,
                            Relationship = "Father",
                            RelativeName = "Sathiyamoorthy"
                        },
                        new
                        {
                            RelativeId = 2,
                            Relationship = "Mother",
                            RelativeName = "Sivakami"
                        },
                        new
                        {
                            RelativeId = 3,
                            Relationship = "Brother",
                            RelativeName = "Rathinam"
                        },
                        new
                        {
                            RelativeId = 4,
                            Relationship = "Sons",
                            RelativeName = "Ashwin&Appu"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
